#!/usr/bin/env python3
"""ZealSync MA3 plugin bundler.

Reads each `ma3/plugins/ZealSync_*.lua` entry plus the shared modules in
`ma3/shared/`, inlines the shared modules into one self-contained Lua
chunk per plugin, and writes a GrandMA3 UserPlugin XML to
`<MA3 plugins folder>/ZealSync_*.xml`. The resulting XML is a single
self-contained file — no `ZealSync_shared/` install on the desk needed.

Shared-module loading on the desk uses runtime path concat
(`GetPath('plugins') .. "/ZealSync_shared/" .. name`), which the
MA3_Tools `plugin_server.py` regex doesn't recognise. So we bundle here
instead of relying on PluginLoader's auto-bundler.

Usage:
    python3 ma3/tools/build_plugin_xml.py             # build all
    python3 ma3/tools/build_plugin_xml.py Markers     # one plugin
"""
from __future__ import annotations

import argparse
import base64
import sys
import uuid
import xml.etree.ElementTree as ET
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
PLUGINS_DIR = REPO_ROOT / "ma3" / "plugins"
SHARED_DIR = REPO_ROOT / "ma3" / "shared"
DEFAULT_INSTALL_DIR = Path(
    "/Users/jake/MALightingTechnology/gma3_library/datapools/plugins"
)
BLOCK_CHARS = 3500


def _format_guid() -> str:
    raw = uuid.uuid4().hex.upper()
    return " ".join(raw[i : i + 2] for i in range(0, 32, 2))


def _split_blocks(text: str, size: int = BLOCK_CHARS) -> list[str]:
    return [text[i : i + size] for i in range(0, len(text), size)]


def _strip_local_load_shared(name: str, src: str) -> str:
    """Remove the inlined `local function load_shared(name) ... end` block.

    Every ZealSync plugin and shared module that uses load_shared inlines
    the same helper (D9). When bundled, those locals shadow the global
    load_shared we install in the preamble, so the inlined dofile path
    fires and tries to read `<plugins root>/ZealSync_shared/...` from
    the desk filesystem (which doesn't exist in a bundled plugin).
    Strip the local definition so the global is visible at call sites.
    """
    needle_start = "local function load_shared(name)"
    start_idx = src.find(needle_start)
    if start_idx == -1:
        return src  # no load_shared in this file (e.g. json.lua)
    closer = "    return mod\nend\n"
    end_idx = src.find(closer, start_idx)
    if end_idx == -1:
        raise RuntimeError(f"{name}: could not locate end of load_shared block")
    end_idx += len(closer)
    return src[:start_idx] + src[end_idx:]


def bundle_source(entry_path: Path) -> str:
    """Inline shared modules into a single Lua chunk.

    Strategy:
    - Read the entry plugin and every shared module.
    - Strip the inlined `local function load_shared` from each (D9
      copy-pasted it everywhere; bundled plugins use one global instead).
    - Prepend a `__ZS_sources` table mapping module name -> factory
      function that runs the module body and returns its value.
    - Prepend a memoising global `load_shared` that consults the table
      instead of touching the filesystem.
    - Hot-reload (D12): if `_G.ZEALSYNC_HOTRELOAD` is set, the cache is
      bypassed and the factory re-runs.
    """
    entry_src = _strip_local_load_shared(entry_path.name, entry_path.read_text("utf-8"))

    shared_sources: dict[str, str] = {}
    for shared_path in sorted(SHARED_DIR.glob("*.lua")):
        body = shared_path.read_text("utf-8")
        shared_sources[shared_path.stem] = _strip_local_load_shared(shared_path.name, body)
    entry_stripped = entry_src

    # Build the preamble. Each shared module body is wrapped as a
    # function so its `return M` survives. We inline the source verbatim
    # — including its own load_shared calls, which will resolve via the
    # global we install just below.
    # Forward-declare load_shared so the factory functions below can
    # capture it as an upvalue. We assign the actual implementation
    # after the __ZS_sources table is populated; the upvalue mutates
    # when the assignment runs, so calls inside the factories see the
    # final function. `local` keeps everything scoped to this chunk —
    # invisible to other plugins sharing the MA3 Lua state.
    preamble_lines: list[str] = [
        "-- ZealSync plugin bundle (generated by ma3/tools/build_plugin_xml.py).",
        "-- Shared modules are inlined here — no ZealSync_shared/ on the desk needed.",
        "local __ZS_sources = {}",
        "local __ZS_loaded = {}",
        "local load_shared",
        "",
    ]
    for name, body in shared_sources.items():
        preamble_lines.append(f"__ZS_sources[{name!r}] = function()")
        preamble_lines.append(body.rstrip())
        preamble_lines.append("end")
        preamble_lines.append("")

    # Hot-reload (D12): if _G.ZEALSYNC_HOTRELOAD, bypass the cache and
    # re-run the factory. Same module-state-reset effect as the
    # dofile-from-disk path on the desk-install workflow.
    preamble_lines.extend([
        "load_shared = function(name)",
        "    if __ZS_loaded[name] ~= nil and not _G.ZEALSYNC_HOTRELOAD then",
        "        return __ZS_loaded[name]",
        "    end",
        "    local factory = __ZS_sources[name]",
        "    if not factory then",
        "        error('ZealSync: unknown shared module: ' .. tostring(name))",
        "    end",
        "    local v = factory()",
        "    __ZS_loaded[name] = v",
        "    return v",
        "end",
        "",
    ])

    return "\n".join(preamble_lines) + entry_stripped


def build_xml(plugin_name: str, source: str) -> str:
    root = ET.Element("GMA3", attrib={"DataVersion": "2.3.2.0"})
    user = ET.SubElement(
        root,
        "UserPlugin",
        attrib={
            "Name": plugin_name,
            "Guid": _format_guid(),
            "Version": "v1",
            "Appearance": "",
        },
    )
    component = ET.SubElement(
        user,
        "ComponentLua",
        attrib={"Guid": _format_guid(), "Name": plugin_name},
    )
    encoded = base64.b64encode(source.encode("utf-8")).decode("ascii")
    blocks = _split_blocks(encoded)
    file_content = ET.SubElement(
        component, "FileContent", attrib={"Size": str(len(blocks))}
    )
    for chunk in blocks:
        ET.SubElement(file_content, "Block", attrib={"Base64": chunk})

    return ET.tostring(root, encoding="utf-8", xml_declaration=True).decode("utf-8")


def discover_entries(filter_suffix: str | None) -> list[Path]:
    entries = sorted(PLUGINS_DIR.glob("ZealSync_*.lua"))
    if filter_suffix:
        entries = [
            p for p in entries if p.stem.lower().endswith(filter_suffix.lower())
        ]
    return entries


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "filter",
        nargs="?",
        help='Plugin suffix to build (e.g. "Markers"). Default: build all.',
    )
    parser.add_argument(
        "--out-dir",
        default=str(DEFAULT_INSTALL_DIR),
        help=f"Output directory. Default: {DEFAULT_INSTALL_DIR}",
    )
    args = parser.parse_args(argv)

    entries = discover_entries(args.filter)
    if not entries:
        print("No matching plugins found.", file=sys.stderr)
        return 1

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    for entry in entries:
        plugin_name = entry.stem
        bundled = bundle_source(entry)
        xml_text = build_xml(plugin_name, bundled)
        out_path = out_dir / f"{plugin_name}.xml"
        out_path.write_text(xml_text, encoding="utf-8")
        print(
            f"wrote {out_path}  ({len(bundled)} bytes lua, {len(xml_text)} bytes xml)"
        )

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
